Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AccueilController",
            "name": "AccueilController",
            "summary": "Contr\u00F4leur\u0020g\u00E9rant\u0020les\u0020pages\u0020du\u0020front\u0020office\u0020\u0028accueil\u0020et\u0020CGU\u0029",
            "url": "classes/App-Controller-AccueilController.html"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020contr\u00F4leur",
            "url": "classes/App-Controller-AccueilController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027accueil",
            "url": "classes/App-Controller-AccueilController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Acgu\u0028\u0029",
            "name": "cgu",
            "summary": "Affiche\u0020la\u0020page\u0020des\u0020conditions\u0020g\u00E9n\u00E9rales\u0020d\u0027utilisation\u0020\u0028CGU\u0029",
            "url": "classes/App-Controller-AccueilController.html#method_cgu"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "Repository\u0020permettant\u0020d\u0027acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020formations",
            "url": "classes/App-Controller-AccueilController.html#property_repository"
        },                {
            "fqsen": "\\App\\Controller\\CategoriesController",
            "name": "CategoriesController",
            "summary": "Contr\u00F4leur\u0020permettant\u0020de\u0020g\u00E9rer\u0020les\u0020cat\u00E9gories\u0020dans\u0020le\u0020back\u0020office",
            "url": "classes/App-Controller-CategoriesController.html"
        },                {
            "fqsen": "\\App\\Controller\\CategoriesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020et\u0020g\u00E8re\u0020l\u0027ajout\u0020d\u0027une\u0020nouvelle\u0020cat\u00E9gorie",
            "url": "classes/App-Controller-CategoriesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\CategoriesController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020cat\u00E9gorie",
            "url": "classes/App-Controller-CategoriesController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController",
            "name": "FormationsController",
            "summary": "Contr\u00F4leur\u0020des\u0020formations",
            "url": "classes/App-Controller-FormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020avec\u0020injection\u0020des\u0020repositories",
            "url": "classes/App-Controller-FormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020formations\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AindexAdmin\u0028\u0029",
            "name": "indexAdmin",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020formations\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_indexAdmin"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Trie\u0020les\u0020formations\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AsortAdmin\u0028\u0029",
            "name": "sortAdmin",
            "summary": "Trie\u0020les\u0020formations\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_sortAdmin"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "Recherche\u0020des\u0020formations\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AfindAllContainAdmin\u0028\u0029",
            "name": "findAllContainAdmin",
            "summary": "Recherche\u0020des\u0020formations\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_findAllContainAdmin"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020formation\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AshowOneAdmin\u0028\u0029",
            "name": "showOneAdmin",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020formation\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-FormationsController.html#method_showOneAdmin"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020nouvelle\u0020formation",
            "url": "classes/App-Controller-FormationsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Modifie\u0020une\u0020formation\u0020existante",
            "url": "classes/App-Controller-FormationsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020formation",
            "url": "classes/App-Controller-FormationsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AFORMATIONS_TEMPLATE",
            "name": "FORMATIONS_TEMPLATE",
            "summary": "Template\u0020utilis\u00E9\u0020pour\u0020le\u0020front\u0020office",
            "url": "classes/App-Controller-FormationsController.html#constant_FORMATIONS_TEMPLATE"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AADMIN_FORMATIONS_TEMPLATE",
            "name": "ADMIN_FORMATIONS_TEMPLATE",
            "summary": "Template\u0020utilis\u00E9\u0020pour\u0020le\u0020back\u0020office",
            "url": "classes/App-Controller-FormationsController.html#constant_ADMIN_FORMATIONS_TEMPLATE"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations",
            "url": "classes/App-Controller-FormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories",
            "url": "classes/App-Controller-FormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "Repository\u0020des\u0020playlists",
            "url": "classes/App-Controller-FormationsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController",
            "name": "PlaylistsController",
            "summary": "Contr\u00F4leur\u0020des\u0020playlists",
            "url": "classes/App-Controller-PlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020avec\u0020injection\u0020des\u0020repositories",
            "url": "classes/App-Controller-PlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020playlists\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AindexAdmin\u0028\u0029",
            "name": "indexAdmin",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020playlists\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_indexAdmin"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Trie\u0020les\u0020playlists\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AsortAdmin\u0028\u0029",
            "name": "sortAdmin",
            "summary": "Trie\u0020les\u0020playlists\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_sortAdmin"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "Recherche\u0020de\u0020playlists\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AfindAllContainAdmin\u0028\u0029",
            "name": "findAllContainAdmin",
            "summary": "Recherche\u0020de\u0020playlists\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_findAllContainAdmin"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020playlist\u0020\u0028front\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AshowOneAdmin\u0028\u0029",
            "name": "showOneAdmin",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020playlist\u0020\u0028back\u0020office\u0029",
            "url": "classes/App-Controller-PlaylistsController.html#method_showOneAdmin"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020playlist",
            "url": "classes/App-Controller-PlaylistsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Modifie\u0020une\u0020playlist",
            "url": "classes/App-Controller-PlaylistsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020playlist",
            "url": "classes/App-Controller-PlaylistsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003APLAYLISTS_TEMPLATE",
            "name": "PLAYLISTS_TEMPLATE",
            "summary": "Template\u0020du\u0020front\u0020office",
            "url": "classes/App-Controller-PlaylistsController.html#constant_PLAYLISTS_TEMPLATE"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AADMIN_PLAYLISTS_TEMPLATE",
            "name": "ADMIN_PLAYLISTS_TEMPLATE",
            "summary": "Template\u0020du\u0020back\u0020office",
            "url": "classes/App-Controller-PlaylistsController.html#constant_ADMIN_PLAYLISTS_TEMPLATE"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "Repository\u0020des\u0020playlists",
            "url": "classes/App-Controller-PlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations",
            "url": "classes/App-Controller-PlaylistsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories",
            "url": "classes/App-Controller-PlaylistsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "Contr\u00F4leur\u0020de\u0020s\u00E9curit\u00E9",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020connexion",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Page\u0020d\u0027entr\u00E9e\u0020du\u0020back\u0020office",
            "url": "classes/App-Controller-SecurityController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "D\u00E9connexion\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Entity\\Categorie",
            "name": "Categorie",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020une\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Entity-Categorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Retourne\u0020le\u0020nom\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "Retourne\u0020les\u0020formations\u0020associ\u00E9es",
            "url": "classes/App-Entity-Categorie.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "Ajoute\u0020une\u0020formation\u0020\u00E0\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "Supprime\u0020une\u0020formation\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Identifiant\u0020unique\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Nom\u0020de\u0020la\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "Liste\u0020des\u0020formations\u0020associ\u00E9es\u0020\u00E0\u0020cette\u0020cat\u00E9gorie",
            "url": "classes/App-Entity-Categorie.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\Formation",
            "name": "Formation",
            "summary": "Entit\u00E9\u0020Formation",
            "url": "classes/App-Entity-Formation.html"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Entity-Formation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAt\u0028\u0029",
            "name": "getPublishedAt",
            "summary": "Retourne\u0020la\u0020date\u0020de\u0020publication",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPublishedAt\u0028\u0029",
            "name": "setPublishedAt",
            "summary": "D\u00E9finit\u0020la\u0020date\u0020de\u0020publication",
            "url": "classes/App-Entity-Formation.html#method_setPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAtString\u0028\u0029",
            "name": "getPublishedAtString",
            "summary": "Retourne\u0020la\u0020date\u0020de\u0020publication\u0020format\u00E9e\u0020\u0028d\/m\/Y\u0029",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAtString"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Retourne\u0020le\u0020titre",
            "url": "classes/App-Entity-Formation.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "D\u00E9finit\u0020le\u0020titre",
            "url": "classes/App-Entity-Formation.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Retourne\u0020la\u0020description",
            "url": "classes/App-Entity-Formation.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "D\u00E9finit\u0020la\u0020description",
            "url": "classes/App-Entity-Formation.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetVideoId\u0028\u0029",
            "name": "getVideoId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020de\u0020la\u0020vid\u00E9o\u0020YouTube",
            "url": "classes/App-Entity-Formation.html#method_getVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetVideoId\u0028\u0029",
            "name": "setVideoId",
            "summary": "D\u00E9finit\u0020l\u0027identifiant\u0020de\u0020la\u0020vid\u00E9o\u0020YouTube",
            "url": "classes/App-Entity-Formation.html#method_setVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetMiniature\u0028\u0029",
            "name": "getMiniature",
            "summary": "Retourne\u0020l\u0027URL\u0020de\u0020la\u0020miniature\u0020\u0028petite\u0020image\u0029",
            "url": "classes/App-Entity-Formation.html#method_getMiniature"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPicture\u0028\u0029",
            "name": "getPicture",
            "summary": "Retourne\u0020l\u0027URL\u0020de\u0020l\u0027image\u0020HD",
            "url": "classes/App-Entity-Formation.html#method_getPicture"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPlaylist\u0028\u0029",
            "name": "getPlaylist",
            "summary": "Retourne\u0020la\u0020playlist\u0020associ\u00E9e",
            "url": "classes/App-Entity-Formation.html#method_getPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPlaylist\u0028\u0029",
            "name": "setPlaylist",
            "summary": "D\u00E9finit\u0020la\u0020playlist\u0020associ\u00E9e",
            "url": "classes/App-Entity-Formation.html#method_setPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetCategories\u0028\u0029",
            "name": "getCategories",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020cat\u00E9gories",
            "url": "classes/App-Entity-Formation.html#method_getCategories"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AaddCategory\u0028\u0029",
            "name": "addCategory",
            "summary": "Ajoute\u0020une\u0020cat\u00E9gorie\u0020\u00E0\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#method_addCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AremoveCategory\u0028\u0029",
            "name": "removeCategory",
            "summary": "Supprime\u0020une\u0020cat\u00E9gorie\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#method_removeCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003ACHEMIN_IMAGE",
            "name": "CHEMIN_IMAGE",
            "summary": "D\u00E9but\u0020de\u0020chemin\u0020vers\u0020les\u0020images\u0020YouTube",
            "url": "classes/App-Entity-Formation.html#constant_CHEMIN_IMAGE"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Identifiant\u0020unique\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024publishedAt",
            "name": "publishedAt",
            "summary": "Date\u0020de\u0020publication\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#property_publishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024title",
            "name": "title",
            "summary": "Titre\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Description\u0020d\u00E9taill\u00E9e\u0020de\u0020la\u0020formation",
            "url": "classes/App-Entity-Formation.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024videoId",
            "name": "videoId",
            "summary": "Identifiant\u0020de\u0020la\u0020vid\u00E9o\u0020YouTube",
            "url": "classes/App-Entity-Formation.html#property_videoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024playlist",
            "name": "playlist",
            "summary": "Playlist\u0020associ\u00E9e\u0020\u00E0\u0020la\u0020formation\u0020\u0028relation\u0020ManyToOne\u0029",
            "url": "classes/App-Entity-Formation.html#property_playlist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024categories",
            "name": "categories",
            "summary": "Liste\u0020des\u0020cat\u00E9gories\u0020associ\u00E9es\u0020\u00E0\u0020la\u0020formation\u0020\u0028relation\u0020ManyToMany\u0029",
            "url": "classes/App-Entity-Formation.html#property_categories"
        },                {
            "fqsen": "\\App\\Entity\\Playlist",
            "name": "Playlist",
            "summary": "Entit\u00E9\u0020Playlist",
            "url": "classes/App-Entity-Playlist.html"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Entity-Playlist.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Retourne\u0020le\u0020nom\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Retourne\u0020la\u0020description\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "D\u00E9finit\u0020la\u0020description\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020formations\u0020associ\u00E9es",
            "url": "classes/App-Entity-Playlist.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "Ajoute\u0020une\u0020formation\u0020\u00E0\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "Supprime\u0020une\u0020formation\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetCategoriesPlaylist\u0028\u0029",
            "name": "getCategoriesPlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020noms\u0020des\u0020cat\u00E9gories\u0020associ\u00E9es\u0020aux\u0020formations\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_getCategoriesPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Identifiant\u0020unique\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Nom\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Description\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "Liste\u0020des\u0020formations\u0020associ\u00E9es\u0020\u00E0\u0020la\u0020playlist\u0020\u0028relation\u0020OneToMany\u0029",
            "url": "classes/App-Entity-Playlist.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "Entit\u00E9\u0020User",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "Retourne\u0020le\u0020nom\u0020d\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020d\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "Retourne\u0020un\u0020identifiant\u0020visuel\u0020unique\u0020pour\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "Retourne\u0020les\u0020r\u00F4les\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "D\u00E9finit\u0020les\u0020r\u00F4les\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Retourne\u0020le\u0020mot\u0020de\u0020passe\u0020hash\u00E9",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "D\u00E9finit\u0020le\u0020mot\u0020de\u0020passe\u0020hash\u00E9",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "Supprime\u0020les\u0020donn\u00E9es\u0020sensibles\u0020temporaires",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Identifiant\u0020unique\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "Nom\u0020d\u0027utilisateur\u0020unique",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "R\u00F4les\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "Mot\u0020de\u0020passe\u0020hash\u00E9",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Form\\CategorieType",
            "name": "CategorieType",
            "summary": "Formulaire\u0020CategorieType",
            "url": "classes/App-Form-CategorieType.html"
        },                {
            "fqsen": "\\App\\Form\\CategorieType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construction\u0020du\u0020formulaire",
            "url": "classes/App-Form-CategorieType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\CategorieType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configuration\u0020des\u0020options\u0020du\u0020formulaire",
            "url": "classes/App-Form-CategorieType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\FormationType",
            "name": "FormationType",
            "summary": "Formulaire\u0020FormationType",
            "url": "classes/App-Form-FormationType.html"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construction\u0020du\u0020formulaire",
            "url": "classes/App-Form-FormationType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configuration\u0020des\u0020options\u0020du\u0020formulaire",
            "url": "classes/App-Form-FormationType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType",
            "name": "PlaylistType",
            "summary": "Formulaire\u0020PlaylistType",
            "url": "classes/App-Form-PlaylistType.html"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construction\u0020du\u0020formulaire",
            "url": "classes/App-Form-PlaylistType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configuration\u0020des\u0020options\u0020du\u0020formulaire",
            "url": "classes/App-Form-PlaylistType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository",
            "name": "CategorieRepository",
            "summary": "Repository\u0020Categorie",
            "url": "classes/App-Repository-CategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Repository-CategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Persiste\u0020une\u0020cat\u00E9gorie\u0020en\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-CategorieRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020cat\u00E9gorie\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-CategorieRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020associ\u00E9es\u0020aux\u0020formations\u0020d\u0027une\u0020playlist",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository",
            "name": "FormationRepository",
            "summary": "Repository\u0020Formation",
            "url": "classes/App-Repository-FormationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Repository-FormationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Persiste\u0020une\u0020formation\u0020en\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-FormationRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020formation\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-FormationRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllOrderBy\u0028\u0029",
            "name": "findAllOrderBy",
            "summary": "Retourne\u0020toutes\u0020les\u0020formations\u0020tri\u00E9es\u0020selon\u0020un\u0020champ\u0020donn\u00E9",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllOrderBy"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Recherche\u0020des\u0020formations\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\u0020donn\u00E9e",
            "url": "classes/App-Repository-FormationRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllLasted\u0028\u0029",
            "name": "findAllLasted",
            "summary": "Retourne\u0020les\u0020N\u0020formations\u0020les\u0020plus\u0020r\u00E9centes",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllLasted"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020formations\u0020associ\u00E9es\u0020\u00E0\u0020une\u0020playlist",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository",
            "name": "PlaylistRepository",
            "summary": "Repository\u0020Playlist",
            "url": "classes/App-Repository-PlaylistRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Repository-PlaylistRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Persiste\u0020une\u0020playlist\u0020en\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-PlaylistRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020playlist\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-PlaylistRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByName\u0028\u0029",
            "name": "findAllOrderByName",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020par\u0020leur\u0020nom",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByName"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Recherche\u0020des\u0020playlists\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\u0020donn\u00E9e",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllForOneFormation\u0028\u0029",
            "name": "findAllForOneFormation",
            "summary": "Retourne\u0020les\u0020playlists\u0020associ\u00E9es\u0020\u00E0\u0020une\u0020formation\u0020donn\u00E9e",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllForOneFormation"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "Repository\u0020User",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Met\u0020\u00E0\u0020jour\u0020automatiquement\u0020le\u0020mot\u0020de\u0020passe\u0020hash\u00E9\u0020d\u0027un\u0020utilisateur",
            "url": "classes/App-Repository-UserRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator",
            "name": "LoginFormAuthenticator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
